core/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpageviews
from django.urls import re_path

from . import views

urlpatterns = [
                  re_path(r'^$', views.index, name='index'),
                  re_path(r'^pages/', include('django.contrib.flatpages.urls')),
                  re_path(r'^admin/', admin.site.urls),
                  re_path(r'^i18n/', include('django.conf.urls.i18n')),

                  # 3rd party

                  # Own Apps
                  re_path(r'^news/', include(('news.urls', 'news'), namespace='news')),
                  re_path(r'^kataloge/', include(('downloads.urls', 'downloads'), namespace='downloads')),
                  re_path(r'^produkte/', include(('products.urls', 'products'), namespace='products')),
                  re_path(r'^messen/', include(('fairs.urls', 'fairs'), namespace='fairs')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Named Staticpages
urlpatterns += [
    re_path(r'^unternehmen/$', views.company, name='company'),
    re_path(r'^impressum/$', flatpageviews.flatpage, {'url': '/impressum/'}, name='impressum'),
    re_path(r'^datenschutz/$', flatpageviews.flatpage, {'url': '/datenschutz/'}, name='datenschutz'),

    re_path(r'^(?P<url>.*/)$', flatpageviews.flatpage, name='page'),
]

products/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^lochsagen/empfehlung$', views.holesawAdvice, name='holesaw_advice'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.list, name='list'),
    re_path(r'^(?P<slug>[\w-]+)/details$', views.product_details, name='product_details'),
    re_path(r'^(?P<slug>[\w-]+)/empfehlungen$', views.product_advices, name='advices'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<id>[0-9]+)/$', views.details_by_id, name='details_by_id'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<type>[\w-]+)/$', views.details, name='details'),
]

products/models.py
# -*- coding: utf-8 -*-
from autoslug import AutoSlugField
from django.db import models
from django.utils.translation import gettext_lazy as _


class Indicator(models.Model):
    """
    Definiere Kennziffern, welche für die Sägeblätter notwendig sind.
    """
    value = models.CharField(_("Kennziffer"), max_length=1024, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    length = models.IntegerField(_("Länge (in mm)"), blank=True, default=0)
    diameter = models.CharField(_("Durchmesser (in mm)"), max_length=255, blank=True, default="")
    C = models.BooleanField("C", blank=True, default=False)
    E = models.BooleanField("E", blank=True, default=False)
    G = models.BooleanField("G", blank=True, default=False)
    H = models.BooleanField("H", blank=True, default=False)
    I = models.BooleanField("I", blank=True, default=False)
    J = models.BooleanField("J", blank=True, default=False)
    L = models.BooleanField("L", blank=True, default=False)
    M = models.BooleanField("M", blank=True, default=False)
    N = models.BooleanField("N", blank=True, default=False)
    O = models.BooleanField("O", blank=True, default=False)
    T = models.BooleanField("T", blank=True, default=False)
    U = models.BooleanField("U", blank=True, default=False)
    V = models.BooleanField("V", blank=True, default=False)
    W = models.BooleanField("W", blank=True, default=False)
    UE = models.BooleanField("Ü", blank=True, default=False)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = _('Kennziffer')
        verbose_name_plural = _('Kennziffern')
        ordering = ('value',)
        app_label = 'products'


class Clamping(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Bild"), null=True, blank=True, upload_to='blades/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Aufnahme')
        verbose_name_plural = _('Aufnahmen')
        app_label = 'products'


class ProductGroup(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    public = models.BooleanField(_("Öffentlich?"), default=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Produktgruppe')
        verbose_name_plural = _('Produktgruppen')
        app_label = 'products'


class SawBlade(models.Model):
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=False)
    type = models.CharField(_("Typ"), max_length=255, blank=True)
    name = models.CharField(_("Bezeichnung"), max_length=255, blank=True)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    group = models.ForeignKey(ProductGroup, verbose_name=_("Produktgruppe"), null=True, blank=True, on_delete=models.SET_NULL)
    clamping = models.ForeignKey(Clamping, verbose_name=_("Aufnahme"), null=True, blank=True, on_delete=models.SET_NULL)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    indicators = models.ManyToManyField(Indicator, verbose_name=_("Kennziffern"), blank=True)

    def __str__(self):
        return self.quality

    class Meta:
        verbose_name = _('Sägeblatt')
        verbose_name_plural = _('Sägeblätter')
        app_label = 'products'


class SableSawBlade(SawBlade):
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall"), max_length=255, blank=True, default=None, null=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz"), max_length=255, blank=True, default=None, null=True)
    cutting_minerals = models.CharField(_("Schnittbereich Mineralisch"), max_length=255, blank=True, default=None, null=True)

    class Meta:
        verbose_name = _('Säbelsägeblatt')
        verbose_name_plural = _('Säbelsägeblätter')
        app_label = 'products'


class HackSawBlade(SableSawBlade):
    accessory = models.BooleanField(_("Zubehörartikel?"), default=False, blank=False)
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)

    class Meta:
        verbose_name = _('Metallhandsägeblatt')
        verbose_name_plural = _('Metallhandsägeblätter')
        app_label = 'products'


class HoleSaw(models.Model):
    ordernr = models.CharField(_("Bestellnr."), max_length=1024, blank=False)
    image = models.ImageField(_("Abbildung"), blank=True, upload_to='blades/')
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    category = models.CharField(_("Kategorie"), max_length=1024, blank=True)
    mounting = models.CharField(_("Aufnahmeschaft"), max_length=1024, blank=True)
    saw_length = models.CharField(_("Lochsägenlänge (in mm)"), max_length=1024, blank=True)
    pilot_drill_length = models.CharField(_("Zentrierbohrerlänge (in mm)"), max_length=1024, blank=True)
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=True)
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)

    def __str__(self):
        return self.ordernr

    class Meta:
        verbose_name = _('Lochsäge')
        verbose_name_plural = _('Lochsägen')
        app_label = 'products'


class HoleSawDiameter(models.Model):
    diameter = models.IntegerField(_("Durchmesser (in mm)"), blank=False)
    blades = models.ManyToManyField(HoleSaw, verbose_name=_("Lochsäge"), blank=True)
    advice = models.BooleanField(_("Aus Empfehlungstabelle?"), default=True, blank=True)
    niro = models.IntegerField(_("NIRO"), null=True, blank=True)
    iron = models.IntegerField(_("Guss"), null=True, blank=True)
    steel = models.IntegerField(_("Stahl"), null=True, blank=True)
    non_ferrous_metals = models.IntegerField(_("Buntmetalle"), null=True, blank=True)
    alu = models.IntegerField(_("Alu"), null=True, blank=True)

    def __str__(self):
        return str(self.diameter)

    class Meta:
        verbose_name = _('Lochsägen-Durchmesser')
        verbose_name_plural = _('Lochsägen-Durchmesser')
        app_label = 'products'


class BandSawBladeIndicator(models.Model):
    value = models.CharField(_("Kennziffer"), max_length=255, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    A = models.CharField("A", max_length=255, blank=True)
    C = models.CharField("C", max_length=255, blank=True)
    E = models.CharField("E", max_length=255, blank=True)
    F = models.CharField("F", max_length=255, blank=True)
    G = models.CharField("G", max_length=255, blank=True)
    H = models.CharField("H", max_length=255, blank=True)
    I = models.CharField("I", max_length=255, blank=True)
    J = models.CharField("J", max_length=255, blank=True)
    L = models.CharField("L", max_length=255, blank=True)
    N = models.CharField("N", max_length=255, blank=True)
    O = models.CharField("O", max_length=255, blank=True)
    S = models.CharField("S", max_length=255, blank=True)
    T = models.CharField("T", max_length=255, blank=True)
    U = models.CharField("U", max_length=255, blank=True)
    V = models.CharField("V", max_length=255, blank=True)
    W = models.CharField("W", max_length=255, blank=True)
    X = models.CharField("X", max_length=255, blank=True)
    Y = models.CharField("Y", max_length=255, blank=True)
    Z = models.CharField("Z", max_length=255, blank=True)
    AE = models.CharField("Ä", max_length=255, blank=True)
    UE = models.CharField("Ü", max_length=255, blank=True)
    star_p = models.CharField("*P", max_length=255, blank=True)
    RP = models.CharField("RP", max_length=255, blank=True)
    SP = models.CharField("SP", max_length=255, blank=True)
    TP = models.CharField("TP", max_length=255, blank=True)
    UP = models.CharField("UP", max_length=255, blank=True)
    VP = models.CharField("VP", max_length=255, blank=True)
    WP = models.CharField("WP", max_length=255, blank=True)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Sägeband-Kennziffer')
        verbose_name_plural = _('Sägeband-Kennziffern')
        app_label = 'products'


class BandSawBlade(SawBlade):
    bandsaw_indicators = models.ManyToManyField(BandSawBladeIndicator, verbose_name=_("Kenziffern"), blank=True)
    type_description = models.CharField(_("Typ Beschreibung"), max_length=255, blank=True)
    type2 = models.CharField(_("2. Typ"), max_length=255, blank=True)
    type2_description = models.CharField(_("2. Typ Beschreibung"), max_length=255, blank=True)
    image2 = models.ImageField(_("2. Produktabbildung"), null=True, blank=True, upload_to='blades/')
    heading = models.CharField(_("Seitentitel"), max_length=255, blank=True)
    cols = models.CharField(_("Spalten"), max_length=1024, blank=True)

    class Meta:
        verbose_name = _('Sägeband')
        verbose_name_plural = _('Sägebänder')
        app_label = 'products'


class JigSawBlade(SawBlade):
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)
    tooth_separation = models.FloatField(_("Zahnteilung (ZpZ)"), blank=True)
    length = models.IntegerField(_("Sägeblattlänge (in mm)"), default=0, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall (in mm)"), max_length=255, blank=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz (in mm)"), max_length=255, blank=True)

products/views.py
from django.shortcuts import get_list_or_404, render

from .models import (BandSawBlade, BandSawBladeIndicator, CircularSawBlade,
                     CircularSawBladeIndicator, HackSawBlade, HoleSaw,
                     HoleSawDiameter, JigSawBlade, ProductGroup, SableSawBlade,
                     SawBlade)


def index(request):
    groups = get_list_or_404(ProductGroup)
    return render(request, 'products/index.html', {'groups': groups})


def list(request, slug):
    blades = None
    other = None
    group = ProductGroup.objects.get(slug=slug)
    if slug == 'maschinensageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'metallstichsageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'sabel-und-spezialsabelsageblatter':
        blades = SableSawBlade.objects.filter(group=group)
    elif slug == 'metallhandsageblatter':
        blades = HackSawBlade.objects.filter(group=group)
    elif slug == 'lochsagen':
        blades = HoleSaw.objects.all()
        other = HoleSawDiameter.objects.filter(advice=False)
    elif slug == 'metallsagebander':
        blades = BandSawBlade.objects.all()
        other = BandSawBladeIndicator.objects.all()
    elif slug == 'pendelhubstichsageblatter':
        blades = JigSawBlade.objects.all()
    elif slug == 'metallkreissageblatter':
        blades = CircularSawBlade.objects.all()
        other = CircularSawBladeIndicator.objects.all().order_by('diameter')
    return render(request, 'products/'+slug+'/overview.html',
                  {'blades': blades,
                   'group': group,
                   'other': other})


def details(request, slug, type):
    blade = SawBlade.objects.get(type=type)
    indicators = blade.indicators.order_by('width')
    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'clamping': blade.clamping,
                   'indicators': indicators})


def details_by_id(request, slug, id):
    """
    Given a slug and a ID it returns a unique blade
    :param slug: slug of productgroup
    :param id: blade id
    :return: blade
    """
    blade = BandSawBlade.objects.get(id=id)
    indicators = blade.bandsaw_indicators.all()

    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'indicators': indicators})


def product_details(request, slug):
    return render(request, 'products/'+slug+'/details.html')


def product_advices(request, slug):
    objects = None
    if slug == 'lochsagen':
        objects = HoleSawDiameter.objects.filter(advice=True)
    return render(request, 'products/'+slug+'/advices.html', {'objects': objects})


def holesawAdvice(request):
    layout = 'holesaw_advice.html'
    diameters = HoleSawDiameter.objects.filter(advice=True)
    group = ProductGroup.objects.get(slug='lochsagen')
    return render(request, 'products/'+layout, {'diameters': diameters,
                                                'group': group})


# ======================================================================================================================
#
# ======================================================================================================================

products/templates/products/maschinensageblatter/details.html
{% extends 'layout_productgroups.html' %}
{% load i18n %}

{% load products_tags %}
{% load thumbnail %}

{% block heading %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>
        {{ blade.quality }}<br>
        <small>{{ blade.description }} <span class="text-orange-bold">{{ blade.type }}</span></small>
      </h1>
    </div>
    <div class="col-md-4">
      <p class="alert bg-orange-lighter" style="margin-top: 21px">
        {% blocktrans %}Der schnelle Weg zu unserer Artikel-Nr.{% endblocktrans %}<br>
        <span class="text-orange-bold">{% trans "Qualität" %}</span> + <span class="text-orange-bold">{% blocktrans %}Kennziffer (Abmessung){% endblocktrans %}</span> + <span class="text-orange-bold">{% trans "ZpZ" %}</span><br>
        {% trans "z.B.:" %}
        <span class="text-orange-bold">
          {{ blade.type }}
        </span> + <span class="text-orange-bold">{{ indicators.0.value }}</span> + <span class="text-orange-bold">L</span> = <span class="text-orange-bold">{{ blade.type }}{{ indicators.0.value }}L</span>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      {% if blade.image %}
        <a href="{{ blade.image.url }}">
          <img src="{{ blade.image|thumbnail_url:'blade_image' }}" alt="blade-image">
        </a>
      {% endif %}
    </div>
    <div class="col-md-6 text-right hidden-sm hidden-xs">
      {% if clamping.image %}
        <a href="{{ clamping.image.url }}">
          <img src="{{ clamping.image|thumbnail_url:'products_clamping' }}" alt="{{ blade.quality }}-clamping">
        </a>
      {% endif %}
    </div>
  </div>

  {% include 'core/edit_item.html' with model="products_sawblade" id=blade.id %}

  <table id="products-sawblade-table" class="table table-condensed table-striped-column table-hover">
    <thead>
      <tr>
        <th colspan="3" class="table-only-white-border-right"></th>
        <th colspan="14" class="table-no-border-color">{% trans "ZpZ" %}</th>
      </tr>
      <tr>
        <th colspan="3" class="table-only-white-border-right"></th>
        <th class="bg-orange-dark table-no-bot-border table-no-top-border table-small-height table-black-border-right" colspan="9">
          {% trans "Normalzahn" %}
        </th>
      </tr>
      <tr>
        <th colspan="3" class="table-only-white-border-right"></th>
        <th class="bg-orange-medium table-no-top-border table-no-bot-border table-small-height table-black-border-right" colspan="9">
          {% trans "Positivzahn" %}
        </th>
        <th class="bg-orange-light table-white-border-right table-no-top-border table-no-bot-border table-small-height" colspan="5">
          {% blocktrans %}Variable Positivzahnung{% endblocktrans %}
        </th>
      </tr>
      <tr>
        <th colspan="2" class="table-white-border-right table-no-bot-border">{% trans "Abmessungen" %}</th>
        <th class="table-white-border-right table-no-bot-border">{% trans "Kennziffer" %}</th>
        <th class="table-no-bot-border">2</th>
        <th class="table-no-bot-border">3</th>
        <th class="table-no-bot-border">4</th>
        <th class="table-no-bot-border">6</th>
        <th class="table-no-bot-border">8</th>
        <th class="table-no-bot-border">10</th>
        <th class="table-no-bot-border">14</th>
        <th class="table-no-bot-border">18</th>
        <th class="table-black-border-right table-no-bot-border">
          22
        </th>
        <th class="table-no-bot-border">2/3</th>
        <th class="table-no-bot-border">3/4</th>
        <th class="table-no-bot-border">4/6</th>
        <th class="table-no-bot-border">6/8</th>
        <th class="table-white-border-right table-no-bot-border">
          8/10
        </th>
        <th class="table-no-bot-border">&Oslash;</th>
      </tr>
      <tr>
        <th class="table-no-top-border">{% blocktrans %}in mm:{% endblocktrans %} {% blocktrans %}B x S{% endblocktrans %}</th>
        <th class="table-white-border-right table-no-top-border">L</th>
        <th class="table-white-border-right table-no-top-border"></th>
        <th class="table-no-top-border">
          <span class="text-orange">...C</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...E</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...G</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...H</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...I</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...J</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...L</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...N</span>
        </th>
        <th class="table-black-border-right table-no-top-border">
          <span class="text-orange">...O</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...T</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...U</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...V</span>
        </th>
        <th class="table-no-top-border">
          <span class="text-orange">...W</span>
        </th>
        <th class="table-white-border-right table-no-top-border">
          <span class="text-orange">...Ü</span>
        </th>
        <th class="table-no-top-border">{% blocktrans %}in mm{% endblocktrans %}</th>
      </tr>
    </thead>
    <tbody>
      {% for indicator in indicators %}
        <tr>
          <td>
            {{ indicator.width }} x {{ indicator.strength }}
          </td>
          <td class="table-white-border-right">
            {{ indicator.length }}
          </td>
          <td class="text-orange-bold table-white-border-right">
            ...{{ indicator.value }}...
          </td>

          <td width="5%" class="indicator-dot">{{ indicator.C|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.E|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.G|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.H|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.I|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.J|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.L|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.N|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot table-black-border-right">{{ indicator.O|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.T|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.U|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.V|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot">{{ indicator.W|check_zpz|safe }}</td>
          <td width="5%" class="indicator-dot table-white-border-right">{{ indicator.UE|check_zpz|safe }}</td>

          <td>{{ indicator.diameter }}</td>

          {% if user.is_staff %}
            <td>
              <a href="{% url 'admin:products_indicator_change' indicator.id %}">
                <i class="fa fa-pencil-square-o"></i>
              </a>
            </td>
          {% endif %}

        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include 'products/include_available_teeth.html' %}

{% endblock %}

products/templates/products/maschinensageblatter/overview.html
{% extends "layout_productgroups.html" %}

{% load static %}
{% load thumbnail %}
{% load i18n %}

{% block heading %}
  <h1>
    {{ group.name }}
  </h1>
{% endblock %}

{% block content %}
  {% include 'products/include_productheader.html' with group=group %}

  {% include 'products/includes/general_advice_sawblades.html' %}

  <hr>

  <h3 class="padding-bottom">{% trans "Produkte" %}</h3>
  <div class="row">
    <div class="col-md-6">
      {% for blade in blades %}
        {% if blade.clamping.name == "Standard" %}
          {% ifchanged %}
            <div class="padding-bottom">
              <a href="{{ blade.clamping.image.url }}">
                <img src="{{ blade.clamping.image|thumbnail_url:'products_clamping' }}" alt="clamping">
              </a>
            </div>
          {% endifchanged %}
          <div class="products-list-item">
            <h4>
              <img src="{% static 'img/other/shark_small_45w.png' %}" alt="">
              <a class="text-normal" href="{% url 'products:details' slug=blade.group.slug type=blade.type %}">
                {{ blade.quality }}
              </a>
              <br>
              <img src="{% static 'img/other/blade_small_45w.png' %}" alt="">
              {{ blade.description }}
              <a href="{% url 'products:details' slug=blade.group.slug type=blade.type %}">
                {{ blade.type }} {% trans "Details" %}
              </a>
            </h4>
          </div>
          {% include 'core/edit_item.html' with model="products_sawblade" id=blade.id %}
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-6">
      {% for blade in blades %}
        {% if blade.clamping.name == "Kasto" %}
          {% ifchanged %}
            <div class="padding-bottom">
              <a href="{{ blade.clamping.image.url }}">
                <img src="{{ blade.clamping.image|thumbnail_url:'products_clamping' }}" alt="clamping">
              </a>
            </div>
          {% endifchanged %}
          <div class="products-list-item">
            <h4>
              <img src="{% static 'img/other/shark_small_45w.png' %}" alt="">
                <a class="text-normal" href="{% url 'products:details' slug=blade.group.slug type=blade.type %}">
                  {{ blade }}
                </a>
              <br>
              <img src="{% static 'img/other/blade_small_45w.png' %}" alt="">
              {{ blade.description }}
              <a href="{% url 'products:details' slug=blade.group.slug type=blade.type %}">
                {{ blade.type }} {% trans "Details" %}
              </a>
            </h4>
          </div>
          {% include 'core/edit_item.html' with model="products_sawblade" id=blade.id %}
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}