core/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpageviews
from django.urls import re_path

from . import views

urlpatterns = [
                  re_path(r'^$', views.index, name='index'),
                  re_path(r'^pages/', include('django.contrib.flatpages.urls')),
                  re_path(r'^admin/', admin.site.urls),
                  re_path(r'^i18n/', include('django.conf.urls.i18n')),

                  # 3rd party

                  # Own Apps
                  re_path(r'^news/', include(('news.urls', 'news'), namespace='news')),
                  re_path(r'^kataloge/', include(('downloads.urls', 'downloads'), namespace='downloads')),
                  re_path(r'^produkte/', include(('products.urls', 'products'), namespace='products')),
                  re_path(r'^messen/', include(('fairs.urls', 'fairs'), namespace='fairs')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Named Staticpages
urlpatterns += [
    re_path(r'^unternehmen/$', views.company, name='company'),
    re_path(r'^impressum/$', flatpageviews.flatpage, {'url': '/impressum/'}, name='impressum'),
    re_path(r'^datenschutz/$', flatpageviews.flatpage, {'url': '/datenschutz/'}, name='datenschutz'),

    re_path(r'^(?P<url>.*/)$', flatpageviews.flatpage, name='page'),
]

products/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^lochsagen/empfehlung$', views.holesawAdvice, name='holesaw_advice'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.list, name='list'),
    re_path(r'^(?P<slug>[\w-]+)/details$', views.product_details, name='product_details'),
    re_path(r'^(?P<slug>[\w-]+)/empfehlungen$', views.product_advices, name='advices'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<id>[0-9]+)/$', views.details_by_id, name='details_by_id'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<type>[\w-]+)/$', views.details, name='details'),
]

products/models.py
# -*- coding: utf-8 -*-
from autoslug import AutoSlugField
from django.db import models
from django.utils.translation import gettext_lazy as _


class Indicator(models.Model):
    """
    Definiere Kennziffern, welche für die Sägeblätter notwendig sind.
    """
    value = models.CharField(_("Kennziffer"), max_length=1024, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    length = models.IntegerField(_("Länge (in mm)"), blank=True, default=0)
    diameter = models.CharField(_("Durchmesser (in mm)"), max_length=255, blank=True, default="")
    C = models.BooleanField("C", blank=True, default=False)
    E = models.BooleanField("E", blank=True, default=False)
    G = models.BooleanField("G", blank=True, default=False)
    H = models.BooleanField("H", blank=True, default=False)
    I = models.BooleanField("I", blank=True, default=False)
    J = models.BooleanField("J", blank=True, default=False)
    L = models.BooleanField("L", blank=True, default=False)
    M = models.BooleanField("M", blank=True, default=False)
    N = models.BooleanField("N", blank=True, default=False)
    O = models.BooleanField("O", blank=True, default=False)
    T = models.BooleanField("T", blank=True, default=False)
    U = models.BooleanField("U", blank=True, default=False)
    V = models.BooleanField("V", blank=True, default=False)
    W = models.BooleanField("W", blank=True, default=False)
    UE = models.BooleanField("Ü", blank=True, default=False)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = _('Kennziffer')
        verbose_name_plural = _('Kennziffern')
        ordering = ('value',)
        app_label = 'products'


class Clamping(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Bild"), null=True, blank=True, upload_to='blades/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Aufnahme')
        verbose_name_plural = _('Aufnahmen')
        app_label = 'products'


class ProductGroup(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    public = models.BooleanField(_("Öffentlich?"), default=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Produktgruppe')
        verbose_name_plural = _('Produktgruppen')
        app_label = 'products'


class SawBlade(models.Model):
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=False)
    type = models.CharField(_("Typ"), max_length=255, blank=True)
    name = models.CharField(_("Bezeichnung"), max_length=255, blank=True)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    group = models.ForeignKey(ProductGroup, verbose_name=_("Produktgruppe"), null=True, blank=True, on_delete=models.SET_NULL)
    clamping = models.ForeignKey(Clamping, verbose_name=_("Aufnahme"), null=True, blank=True, on_delete=models.SET_NULL)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    indicators = models.ManyToManyField(Indicator, verbose_name=_("Kennziffern"), blank=True)

    def __str__(self):
        return self.quality

    class Meta:
        verbose_name = _('Sägeblatt')
        verbose_name_plural = _('Sägeblätter')
        app_label = 'products'


class SableSawBlade(SawBlade):
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall"), max_length=255, blank=True, default=None, null=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz"), max_length=255, blank=True, default=None, null=True)
    cutting_minerals = models.CharField(_("Schnittbereich Mineralisch"), max_length=255, blank=True, default=None, null=True)

    class Meta:
        verbose_name = _('Säbelsägeblatt')
        verbose_name_plural = _('Säbelsägeblätter')
        app_label = 'products'


class HackSawBlade(SableSawBlade):
    accessory = models.BooleanField(_("Zubehörartikel?"), default=False, blank=False)
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)

    class Meta:
        verbose_name = _('Metallhandsägeblatt')
        verbose_name_plural = _('Metallhandsägeblätter')
        app_label = 'products'


class HoleSaw(models.Model):
    ordernr = models.CharField(_("Bestellnr."), max_length=1024, blank=False)
    image = models.ImageField(_("Abbildung"), blank=True, upload_to='blades/')
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    category = models.CharField(_("Kategorie"), max_length=1024, blank=True)
    mounting = models.CharField(_("Aufnahmeschaft"), max_length=1024, blank=True)
    saw_length = models.CharField(_("Lochsägenlänge (in mm)"), max_length=1024, blank=True)
    pilot_drill_length = models.CharField(_("Zentrierbohrerlänge (in mm)"), max_length=1024, blank=True)
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=True)
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)

    def __str__(self):
        return self.ordernr

    class Meta:
        verbose_name = _('Lochsäge')
        verbose_name_plural = _('Lochsägen')
        app_label = 'products'


class HoleSawDiameter(models.Model):
    diameter = models.IntegerField(_("Durchmesser (in mm)"), blank=False)
    blades = models.ManyToManyField(HoleSaw, verbose_name=_("Lochsäge"), blank=True)
    advice = models.BooleanField(_("Aus Empfehlungstabelle?"), default=True, blank=True)
    niro = models.IntegerField(_("NIRO"), null=True, blank=True)
    iron = models.IntegerField(_("Guss"), null=True, blank=True)
    steel = models.IntegerField(_("Stahl"), null=True, blank=True)
    non_ferrous_metals = models.IntegerField(_("Buntmetalle"), null=True, blank=True)
    alu = models.IntegerField(_("Alu"), null=True, blank=True)

    def __str__(self):
        return str(self.diameter)

    class Meta:
        verbose_name = _('Lochsägen-Durchmesser')
        verbose_name_plural = _('Lochsägen-Durchmesser')
        app_label = 'products'


class BandSawBladeIndicator(models.Model):
    value = models.CharField(_("Kennziffer"), max_length=255, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    A = models.CharField("A", max_length=255, blank=True)
    C = models.CharField("C", max_length=255, blank=True)
    E = models.CharField("E", max_length=255, blank=True)
    F = models.CharField("F", max_length=255, blank=True)
    G = models.CharField("G", max_length=255, blank=True)
    H = models.CharField("H", max_length=255, blank=True)
    I = models.CharField("I", max_length=255, blank=True)
    J = models.CharField("J", max_length=255, blank=True)
    L = models.CharField("L", max_length=255, blank=True)
    N = models.CharField("N", max_length=255, blank=True)
    O = models.CharField("O", max_length=255, blank=True)
    S = models.CharField("S", max_length=255, blank=True)
    T = models.CharField("T", max_length=255, blank=True)
    U = models.CharField("U", max_length=255, blank=True)
    V = models.CharField("V", max_length=255, blank=True)
    W = models.CharField("W", max_length=255, blank=True)
    X = models.CharField("X", max_length=255, blank=True)
    Y = models.CharField("Y", max_length=255, blank=True)
    Z = models.CharField("Z", max_length=255, blank=True)
    AE = models.CharField("Ä", max_length=255, blank=True)
    UE = models.CharField("Ü", max_length=255, blank=True)
    star_p = models.CharField("*P", max_length=255, blank=True)
    RP = models.CharField("RP", max_length=255, blank=True)
    SP = models.CharField("SP", max_length=255, blank=True)
    TP = models.CharField("TP", max_length=255, blank=True)
    UP = models.CharField("UP", max_length=255, blank=True)
    VP = models.CharField("VP", max_length=255, blank=True)
    WP = models.CharField("WP", max_length=255, blank=True)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Sägeband-Kennziffer')
        verbose_name_plural = _('Sägeband-Kennziffern')
        app_label = 'products'


class BandSawBlade(SawBlade):
    bandsaw_indicators = models.ManyToManyField(BandSawBladeIndicator, verbose_name=_("Kenziffern"), blank=True)
    type_description = models.CharField(_("Typ Beschreibung"), max_length=255, blank=True)
    type2 = models.CharField(_("2. Typ"), max_length=255, blank=True)
    type2_description = models.CharField(_("2. Typ Beschreibung"), max_length=255, blank=True)
    image2 = models.ImageField(_("2. Produktabbildung"), null=True, blank=True, upload_to='blades/')
    heading = models.CharField(_("Seitentitel"), max_length=255, blank=True)
    cols = models.CharField(_("Spalten"), max_length=1024, blank=True)

    class Meta:
        verbose_name = _('Sägeband')
        verbose_name_plural = _('Sägebänder')
        app_label = 'products'


class JigSawBlade(SawBlade):
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)
    tooth_separation = models.FloatField(_("Zahnteilung (ZpZ)"), blank=True)
    length = models.IntegerField(_("Sägeblattlänge (in mm)"), default=0, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall (in mm)"), max_length=255, blank=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz (in mm)"), max_length=255, blank=True)

products/views.py
from django.shortcuts import get_list_or_404, render

from .models import (BandSawBlade, BandSawBladeIndicator, CircularSawBlade,
                     CircularSawBladeIndicator, HackSawBlade, HoleSaw,
                     HoleSawDiameter, JigSawBlade, ProductGroup, SableSawBlade,
                     SawBlade)


def index(request):
    groups = get_list_or_404(ProductGroup)
    return render(request, 'products/index.html', {'groups': groups})


def list(request, slug):
    blades = None
    other = None
    group = ProductGroup.objects.get(slug=slug)
    if slug == 'maschinensageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'metallstichsageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'sabel-und-spezialsabelsageblatter':
        blades = SableSawBlade.objects.filter(group=group)
    elif slug == 'metallhandsageblatter':
        blades = HackSawBlade.objects.filter(group=group)
    elif slug == 'lochsagen':
        blades = HoleSaw.objects.all()
        other = HoleSawDiameter.objects.filter(advice=False)
    elif slug == 'metallsagebander':
        blades = BandSawBlade.objects.all()
        other = BandSawBladeIndicator.objects.all()
    elif slug == 'pendelhubstichsageblatter':
        blades = JigSawBlade.objects.all()
    elif slug == 'metallkreissageblatter':
        blades = CircularSawBlade.objects.all()
        other = CircularSawBladeIndicator.objects.all().order_by('diameter')
    return render(request, 'products/'+slug+'/overview.html',
                  {'blades': blades,
                   'group': group,
                   'other': other})


def details(request, slug, type):
    blade = SawBlade.objects.get(type=type)
    indicators = blade.indicators.order_by('width')
    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'clamping': blade.clamping,
                   'indicators': indicators})


def details_by_id(request, slug, id):
    """
    Given a slug and a ID it returns a unique blade
    :param slug: slug of productgroup
    :param id: blade id
    :return: blade
    """
    blade = BandSawBlade.objects.get(id=id)
    indicators = blade.bandsaw_indicators.all()

    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'indicators': indicators})


def product_details(request, slug):
    return render(request, 'products/'+slug+'/details.html')


def product_advices(request, slug):
    objects = None
    if slug == 'lochsagen':
        objects = HoleSawDiameter.objects.filter(advice=True)
    return render(request, 'products/'+slug+'/advices.html', {'objects': objects})


def holesawAdvice(request):
    layout = 'holesaw_advice.html'
    diameters = HoleSawDiameter.objects.filter(advice=True)
    group = ProductGroup.objects.get(slug='lochsagen')
    return render(request, 'products/'+layout, {'diameters': diameters,
                                                'group': group})


# ======================================================================================================================
#
# ======================================================================================================================

products/templates/products/includes/general_advice_sawblades.html
{% load static %}
{% load thumbnail %}
{% load i18n %}

{% if not no_advice %}
  <p class="pull-right">
    <a class="btn btn-primary" role="button" href="{% url 'products:advices' slug=group.slug %}">
      {% trans "Zu unseren Empfehlungen" %}
    </a>
    {% comment %}
    <a class="btn btn-primary" role="button" data-toggle="collapse" href="#collapse-1" aria-expanded="false" aria-controls="collapse-1">
      {% trans "Details anzeigen" %}
      <span class="caret"></span>
    </a>
    {% endcomment %}
  </p>
{% endif %}

{# <div id="collapse-1" class="collapse"> #}
<div id="collapse-1">
  <h3>{% trans "Material, Qualitäten und Einsatzbereiche" %}</h3>
  <p>
    {% trans "Unser Streben nach perfekter Sägequalität beginnt schon bei der Auswahl unseres Vormaterials, denn dies ist die Ausgangsbasis für unsere Spitzenprodukte – nichts geht durch unsere Eingangskontrolle, das nicht die Note „Sehr gut“ verdient." %}
  </p>
  <p>
    {% trans "Erstklassiges Rohmaterial ist bei GUHEMA die Basis für präzises, schnelles und wirtschaftliches Sägen mit" %}
  </p>
  <ul>
    <li>{% trans "hohen Stand- und kurzen Schnittzeiten" %}</li>
    <li>{% trans "langer Lebensdauer" %}</li>
    <li>{% trans "optimaler Schonung Ihrer Sägemaschine" %}</li>
  </ul>
  <p>
    {% trans "Für die unterschiedlichsten Einsatzbereiche führen wir die passenden Qualitäten" %}
  </p>

  <div class="well">
    <div>
      <img src="{% static 'img/other/shark_small_45w.png' %}" alt="">
      GUHEMA Super-HSS
    </div>
    <div>
      <img src="{% static 'img/other/blade_small_45w.png' %}" alt="">
      {% blocktrans with num="1.3343" %}DMo 5 Qualität (Werkstoff-Nr. {{ num }}){% endblocktrans %}
    </div>
    <div>
      <img src="{% static 'img/other/tool_small_45w.png' %}" alt="">
      {% trans "Für Werkstoffe bis zu einer Zugfestigkeit von 1100 N/mm<sup>2</sup>" %}
    </div>

    <div class="padding-top-05">
      <div>
        <img src="{% static 'img/other/shark_small_45w.png' %}" alt="">
        GUHEMA Brillant
      </div>
      <div>
        <img src="{% static 'img/other/blade_small_45w.png' %}" alt="">
        {% blocktrans with num="1.3243" %}EMo 5 Co 5 Qualität (Werkstoff-Nr. {{ num }}){% endblocktrans %}
      </div>
      <div>
        <img src="{% static 'img/other/tool_small_45w.png' %}" alt="">
        {% trans "Für extrem harte Werkstoffe bis 1300 N/mm<sup>2</sup> z.B. austenitische Stähle und Stähle mit hohem Chrom-Nickelgehalt" %}
      </div>
    </div>

    <div class="padding-top-05">
      <div>
        <img src="{% static 'img/other/shark_small_45w.png' %}" alt="">
        GUHEMA Bi-lastic
      </div>
      <div>
        <img src="{% static 'img/other/blade_small_45w.png' %}" alt="">
        {% blocktrans with num="1.3343" %}DMo 5 Schneidenqualität (Werkstoff-Nr. {{ num }}) auf einem Sonderstahlrücken{% endblocktrans %}
      </div>
      <div>
        <img src="{% static 'img/other/tool_small_45w.png' %}" alt="">
        {% trans "Für Werkstoffe bis zu einer Zugfestigkeit von 1100 N/mm<sup>2</sup>" %}
      </div>
    </div>
  </div>

  <h3>{% trans "Die Wahl der richtigen Zahnform" %}</h3>
  <p>
    {% trans "Unsere GUHEMA-Maschinensägeblätter haben erst durch die richtige Zahnform den optimalen Biss. Wir liefern:" %}
  </p>

  <div class="row">
    <div class="col-md-6 padding-top-3">
      <span class="bg-orange-dark padding-lr-1 text-bold">
        {% trans "Normalzahn" %}
      </span>
      <p>
        {% trans "Für den allgemeinen, universellen Einsatz" %}
      </p>
    </div>
    <div class="col-md-6 text-right">
      {% include 'products/includes/image_multilang.html' with path_to_image='img/produktbilder/maschinensaegeblaetter/katalog_2014/normalverzahnung_' extension='.png' alt_text='Normalzahn' width='400px' nothumbnail=True %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 padding-top-3">
      <span class="bg-orange-medium padding-lr-1 text-bold">
        {% trans "Positivzahn" %}
      </span>
      <p>
        {% trans "Der austenitische, zähharte Stähle trennt" %}
      </p>
    </div>
    <div class="col-md-6 text-right">
      {% include 'products/includes/image_multilang.html' with path_to_image='img/produktbilder/maschinensaegeblaetter/katalog_2014/positivverzahnung_' extension='.png' alt_text='Normalzahn' width='400px' nothumbnail=True %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 padding-top-3">
      <span class="bg-orange-light padding-lr-1 text-bold">
        {% trans "Variable Positivverzahnung" %}
      </span>
      <p>
        {% trans "GUHEMA FUTURE, die keine Wünsche an ein Maschinensägeblatt mehr offen lässt" %}
      </p>
    </div>
    <div class="col-md-6 text-right">
      {% include 'products/includes/image_multilang.html' with path_to_image='img/produktbilder/maschinensaegeblaetter/katalog_2014/variable_positivverzahnung_' extension='.png' alt_text='Normalzahn' width='400px' nothumbnail=True %}
    </div>
  </div>

</div>

products/templates/products/includes/image_multilang.html
{% load i18n %}
{% load static %}

{% get_current_language as lang %}

{% with path_to_image|add:lang|add:extension as image %}
  {% static image as img %}
  <div class="padding-top">
    <a href="{{ img }}">
      <img class="img-responsive {% if not nothumbnail %}img-thumbnail{% endif %}" src="{{ img }}" alt="{{ alt_text }}"
           {% if width %}width="{{ width }}"{% endif %}>
    </a>
  </div>
{% endwith %}