core/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpageviews
from django.urls import re_path

from . import views

urlpatterns = [
                  re_path(r'^$', views.index, name='index'),
                  re_path(r'^pages/', include('django.contrib.flatpages.urls')),
                  re_path(r'^admin/', admin.site.urls),
                  re_path(r'^i18n/', include('django.conf.urls.i18n')),

                  # 3rd party

                  # Own Apps
                  re_path(r'^news/', include(('news.urls', 'news'), namespace='news')),
                  re_path(r'^kataloge/', include(('downloads.urls', 'downloads'), namespace='downloads')),
                  re_path(r'^produkte/', include(('products.urls', 'products'), namespace='products')),
                  re_path(r'^messen/', include(('fairs.urls', 'fairs'), namespace='fairs')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Named Staticpages
urlpatterns += [
    re_path(r'^unternehmen/$', views.company, name='company'),
    re_path(r'^impressum/$', flatpageviews.flatpage, {'url': '/impressum/'}, name='impressum'),
    re_path(r'^datenschutz/$', flatpageviews.flatpage, {'url': '/datenschutz/'}, name='datenschutz'),

    re_path(r'^(?P<url>.*/)$', flatpageviews.flatpage, name='page'),
]

news/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.overview, {'category': 'Allgemein'}, name='overview'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
]

news/models.py
from datetime import datetime

from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(_('Name'), max_length=50, blank=False)
    intro = models.TextField(_('Kurzbeschreibung'), blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Kategorie')
        verbose_name_plural = _('Kategorien')


class Entry(models.Model):
    title = models.CharField(_('Titel'), max_length=50, blank=False)
    author = models.ForeignKey(User, null=True, blank=True, verbose_name=_("Autor"), on_delete=models.SET_NULL)
    content = models.TextField(_('Inhalt'), blank=False)
    image = models.ImageField(_('Bild'), null=True, blank=True)
    attachment = models.FileField(_('Anhang'), null=True, blank=True)
    slug = AutoSlugField(null=True, populate_from='title')
    archive = models.BooleanField(_('Archiviert?'), default=False)
    public = models.BooleanField(_('Öffentlich?'), default=True)
    created = models.DateTimeField(_('Erstellt am'), default=datetime.now)
    category = models.ForeignKey(Category, null=True, verbose_name=_("Kategorie"), on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return 'news:entry', (self.slug,)

    class Meta:
        verbose_name = _('Eintrag')
        verbose_name_plural = _('Einträge')
        ordering = ('created',)

news/views.py
from django.shortcuts import get_list_or_404, get_object_or_404, render

from .models import Entry


def detail(request, slug):
    entry = get_object_or_404(Entry, slug=slug)
    return render(request, 'news/detail.html', {'entry': entry})


def overview(request, page=1, category="Allgemein"):
    posts = get_list_or_404(Entry.objects.order_by('-created'))
    return render(request, 'news/overview.html',
                  {'posts':     posts,
                   'category':  category[0]})

news/templates/news/detail.html
{% extends "layout_productgroups.html" %}
{% load i18n %}
{% load thumbnail %}
{% load markdownify %}

{% block heading %}
  <h1>{{ entry.title }}</h1>
  <h4>
    <small>
      {{ entry.created|date:"j. N Y" }}{% if entry.author %}{% endif %}
      {% include 'core/edit_item.html' with model="news_entry" id=entry.id %}
    </small>
  </h4>
{% endblock %}

{% block content %}
  {% if entry.image %}
    <div id="news-detail-image">
      <img class="img-responsive" src="{{ entry.image|thumbnail_url:'news_detail' }}" alt="{{ entry.title }}-image">
    </div>
  {% endif %}

  {{ entry.content|safe|markdownify }}

  {% if entry.attachment %}
    <div class="padding-top">
      <p>
        <i class="fa fa-download"></i> <a href="{{ entry.attachment.url }}">{{ entry.attachment.name|slice:"2:" }}</a>
      </p>
    </div>
  {% endif %}

{% endblock %}

news/templates/news/inc_overview.html
{% load thumbnail %}
{% load static %}
{% load news_extras %}
{% load markdownify %}

{% for post in posts %}
  {% if forloop.counter|mod:3 or forloop.first %}
    <div class="row news-row">
  {% endif %}
<div class="col-md-4 col-xs-12">
  <div id="news-header">
    <div id="news-image">
      <a href="{% url 'news:detail' slug=post.slug %}">
        {% if post.image %}
          <img src="{{ post.image|thumbnail_url:'news_front' }}" class="img-responsive" alt="{{ post.title }}"/>
        {% else %}
          <img src="{% static 'img/news/news_placeholder_360.jpg' %}" class="img-responsive" alt="{{ post.title }}"/>
        {% endif %}
      </a>
    </div>
    <div class="row">
      <div class="col-md-2 col-sm-1 col-xs-2">
        <div id="cube">
          <div id="cube-content">
            <strong>{{ post.created|date:"N" }}</strong><br>
            {{ post.created|date:"Y" }}
          </div>
        </div>
      </div>
      <div id="news-title" class="col-md-9 col-sm-11 col-xs-10">
        <h4>
          <a href="{% url 'news:detail' slug=post.slug %}">
            {{ post.title }}
          </a>
        </h4>
      </div>
    </div>
  </div>
  <div id="news-content" class="padding-bottom">
    <p>
      {{ post.content|safe|markdownify }}
    </p>
    {% include 'core/edit_item.html' with model="news_entry" id=post.id %}
  </div>
</div>
{% if forloop.counter|mod:3 and not forloop.first %}
  </div>
{% endif %}
{% endfor %}

news/templates/news/overview.html
{% extends 'layout_productgroups.html' %}
{% load i18n %}

{% block heading %}
  <h1>{% trans "News" %}</h1>
{% endblock %}

{% block content %}
  {% include 'news/inc_overview.html' with posts=posts %}
{% endblock %}