core/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages import views as flatpageviews
from django.urls import re_path

from . import views

urlpatterns = [
                  re_path(r'^$', views.index, name='index'),
                  re_path(r'^pages/', include('django.contrib.flatpages.urls')),
                  re_path(r'^admin/', admin.site.urls),
                  re_path(r'^i18n/', include('django.conf.urls.i18n')),

                  # 3rd party

                  # Own Apps
                  re_path(r'^news/', include(('news.urls', 'news'), namespace='news')),
                  re_path(r'^kataloge/', include(('downloads.urls', 'downloads'), namespace='downloads')),
                  re_path(r'^produkte/', include(('products.urls', 'products'), namespace='products')),
                  re_path(r'^messen/', include(('fairs.urls', 'fairs'), namespace='fairs')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Named Staticpages
urlpatterns += [
    re_path(r'^unternehmen/$', views.company, name='company'),
    re_path(r'^impressum/$', flatpageviews.flatpage, {'url': '/impressum/'}, name='impressum'),
    re_path(r'^datenschutz/$', flatpageviews.flatpage, {'url': '/datenschutz/'}, name='datenschutz'),

    re_path(r'^(?P<url>.*/)$', flatpageviews.flatpage, name='page'),
]

news/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.overview, {'category': 'Allgemein'}, name='overview'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.detail, name='detail'),
]

products/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^lochsagen/empfehlung$', views.holesawAdvice, name='holesaw_advice'),
    re_path(r'^(?P<slug>[\w-]+)/$', views.list, name='list'),
    re_path(r'^(?P<slug>[\w-]+)/details$', views.product_details, name='product_details'),
    re_path(r'^(?P<slug>[\w-]+)/empfehlungen$', views.product_advices, name='advices'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<id>[0-9]+)/$', views.details_by_id, name='details_by_id'),
    re_path(r'^(?P<slug>[\w-]+)/(?P<type>[\w-]+)/$', views.details, name='details'),
]

products/models.py
# -*- coding: utf-8 -*-
from autoslug import AutoSlugField
from django.db import models
from django.utils.translation import gettext_lazy as _


class Indicator(models.Model):
    """
    Definiere Kennziffern, welche für die Sägeblätter notwendig sind.
    """
    value = models.CharField(_("Kennziffer"), max_length=1024, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    length = models.IntegerField(_("Länge (in mm)"), blank=True, default=0)
    diameter = models.CharField(_("Durchmesser (in mm)"), max_length=255, blank=True, default="")
    C = models.BooleanField("C", blank=True, default=False)
    E = models.BooleanField("E", blank=True, default=False)
    G = models.BooleanField("G", blank=True, default=False)
    H = models.BooleanField("H", blank=True, default=False)
    I = models.BooleanField("I", blank=True, default=False)
    J = models.BooleanField("J", blank=True, default=False)
    L = models.BooleanField("L", blank=True, default=False)
    M = models.BooleanField("M", blank=True, default=False)
    N = models.BooleanField("N", blank=True, default=False)
    O = models.BooleanField("O", blank=True, default=False)
    T = models.BooleanField("T", blank=True, default=False)
    U = models.BooleanField("U", blank=True, default=False)
    V = models.BooleanField("V", blank=True, default=False)
    W = models.BooleanField("W", blank=True, default=False)
    UE = models.BooleanField("Ü", blank=True, default=False)

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = _('Kennziffer')
        verbose_name_plural = _('Kennziffern')
        ordering = ('value',)
        app_label = 'products'


class Clamping(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Bild"), null=True, blank=True, upload_to='blades/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Aufnahme')
        verbose_name_plural = _('Aufnahmen')
        app_label = 'products'


class ProductGroup(models.Model):
    name = models.CharField(_("Name"), max_length=255, blank=False)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    public = models.BooleanField(_("Öffentlich?"), default=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Produktgruppe')
        verbose_name_plural = _('Produktgruppen')
        app_label = 'products'


class SawBlade(models.Model):
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=False)
    type = models.CharField(_("Typ"), max_length=255, blank=True)
    name = models.CharField(_("Bezeichnung"), max_length=255, blank=True)
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    group = models.ForeignKey(ProductGroup, verbose_name=_("Produktgruppe"), null=True, blank=True, on_delete=models.SET_NULL)
    clamping = models.ForeignKey(Clamping, verbose_name=_("Aufnahme"), null=True, blank=True, on_delete=models.SET_NULL)
    slug = AutoSlugField(null=True, populate_from='name')
    image = models.ImageField(_("Produktabbildung"), null=True, blank=True, upload_to='blades/')
    indicators = models.ManyToManyField(Indicator, verbose_name=_("Kennziffern"), blank=True)

    def __str__(self):
        return self.quality

    class Meta:
        verbose_name = _('Sägeblatt')
        verbose_name_plural = _('Sägeblätter')
        app_label = 'products'


class SableSawBlade(SawBlade):
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall"), max_length=255, blank=True, default=None, null=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz"), max_length=255, blank=True, default=None, null=True)
    cutting_minerals = models.CharField(_("Schnittbereich Mineralisch"), max_length=255, blank=True, default=None, null=True)

    class Meta:
        verbose_name = _('Säbelsägeblatt')
        verbose_name_plural = _('Säbelsägeblätter')
        app_label = 'products'


class HackSawBlade(SableSawBlade):
    accessory = models.BooleanField(_("Zubehörartikel?"), default=False, blank=False)
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)

    class Meta:
        verbose_name = _('Metallhandsägeblatt')
        verbose_name_plural = _('Metallhandsägeblätter')
        app_label = 'products'


class HoleSaw(models.Model):
    ordernr = models.CharField(_("Bestellnr."), max_length=1024, blank=False)
    image = models.ImageField(_("Abbildung"), blank=True, upload_to='blades/')
    description = models.TextField(_("Beschreibung"), max_length=1024, blank=True)
    category = models.CharField(_("Kategorie"), max_length=1024, blank=True)
    mounting = models.CharField(_("Aufnahmeschaft"), max_length=1024, blank=True)
    saw_length = models.CharField(_("Lochsägenlänge (in mm)"), max_length=1024, blank=True)
    pilot_drill_length = models.CharField(_("Zentrierbohrerlänge (in mm)"), max_length=1024, blank=True)
    quality = models.CharField(_("Stahlsorte"), max_length=255, blank=True)
    toothing = models.CharField(_("Verzahnung"), max_length=255, blank=True)

    def __str__(self):
        return self.ordernr

    class Meta:
        verbose_name = _('Lochsäge')
        verbose_name_plural = _('Lochsägen')
        app_label = 'products'


class HoleSawDiameter(models.Model):
    diameter = models.IntegerField(_("Durchmesser (in mm)"), blank=False)
    blades = models.ManyToManyField(HoleSaw, verbose_name=_("Lochsäge"), blank=True)
    advice = models.BooleanField(_("Aus Empfehlungstabelle?"), default=True, blank=True)
    niro = models.IntegerField(_("NIRO"), null=True, blank=True)
    iron = models.IntegerField(_("Guss"), null=True, blank=True)
    steel = models.IntegerField(_("Stahl"), null=True, blank=True)
    non_ferrous_metals = models.IntegerField(_("Buntmetalle"), null=True, blank=True)
    alu = models.IntegerField(_("Alu"), null=True, blank=True)

    def __str__(self):
        return str(self.diameter)

    class Meta:
        verbose_name = _('Lochsägen-Durchmesser')
        verbose_name_plural = _('Lochsägen-Durchmesser')
        app_label = 'products'


class BandSawBladeIndicator(models.Model):
    value = models.CharField(_("Kennziffer"), max_length=255, blank=False)
    width = models.IntegerField(_("Breite (in mm)"), blank=True, default=0)
    strength = models.FloatField(_("Stärke (in mm)"), blank=True, default=0)
    A = models.CharField("A", max_length=255, blank=True)
    C = models.CharField("C", max_length=255, blank=True)
    E = models.CharField("E", max_length=255, blank=True)
    F = models.CharField("F", max_length=255, blank=True)
    G = models.CharField("G", max_length=255, blank=True)
    H = models.CharField("H", max_length=255, blank=True)
    I = models.CharField("I", max_length=255, blank=True)
    J = models.CharField("J", max_length=255, blank=True)
    L = models.CharField("L", max_length=255, blank=True)
    N = models.CharField("N", max_length=255, blank=True)
    O = models.CharField("O", max_length=255, blank=True)
    S = models.CharField("S", max_length=255, blank=True)
    T = models.CharField("T", max_length=255, blank=True)
    U = models.CharField("U", max_length=255, blank=True)
    V = models.CharField("V", max_length=255, blank=True)
    W = models.CharField("W", max_length=255, blank=True)
    X = models.CharField("X", max_length=255, blank=True)
    Y = models.CharField("Y", max_length=255, blank=True)
    Z = models.CharField("Z", max_length=255, blank=True)
    AE = models.CharField("Ä", max_length=255, blank=True)
    UE = models.CharField("Ü", max_length=255, blank=True)
    star_p = models.CharField("*P", max_length=255, blank=True)
    RP = models.CharField("RP", max_length=255, blank=True)
    SP = models.CharField("SP", max_length=255, blank=True)
    TP = models.CharField("TP", max_length=255, blank=True)
    UP = models.CharField("UP", max_length=255, blank=True)
    VP = models.CharField("VP", max_length=255, blank=True)
    WP = models.CharField("WP", max_length=255, blank=True)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = _('Sägeband-Kennziffer')
        verbose_name_plural = _('Sägeband-Kennziffern')
        app_label = 'products'


class BandSawBlade(SawBlade):
    bandsaw_indicators = models.ManyToManyField(BandSawBladeIndicator, verbose_name=_("Kenziffern"), blank=True)
    type_description = models.CharField(_("Typ Beschreibung"), max_length=255, blank=True)
    type2 = models.CharField(_("2. Typ"), max_length=255, blank=True)
    type2_description = models.CharField(_("2. Typ Beschreibung"), max_length=255, blank=True)
    image2 = models.ImageField(_("2. Produktabbildung"), null=True, blank=True, upload_to='blades/')
    heading = models.CharField(_("Seitentitel"), max_length=255, blank=True)
    cols = models.CharField(_("Spalten"), max_length=1024, blank=True)

    class Meta:
        verbose_name = _('Sägeband')
        verbose_name_plural = _('Sägebänder')
        app_label = 'products'


class JigSawBlade(SawBlade):
    subcategory = models.CharField(_("Unterkategorie"), max_length=255, blank=True)
    tooth_separation = models.FloatField(_("Zahnteilung (ZpZ)"), blank=True)
    length = models.IntegerField(_("Sägeblattlänge (in mm)"), default=0, blank=True)
    cutting_metal = models.CharField(_("Schnittbereich Metall (in mm)"), max_length=255, blank=True)
    cutting_wood = models.CharField(_("Schnittbereich Holz (in mm)"), max_length=255, blank=True)

products/views.py
from django.shortcuts import get_list_or_404, render

from .models import (BandSawBlade, BandSawBladeIndicator, CircularSawBlade,
                     CircularSawBladeIndicator, HackSawBlade, HoleSaw,
                     HoleSawDiameter, JigSawBlade, ProductGroup, SableSawBlade,
                     SawBlade)


def index(request):
    groups = get_list_or_404(ProductGroup)
    return render(request, 'products/index.html', {'groups': groups})


def list(request, slug):
    blades = None
    other = None
    group = ProductGroup.objects.get(slug=slug)
    if slug == 'maschinensageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'metallstichsageblatter':
        blades = SawBlade.objects.filter(group=group)
    elif slug == 'sabel-und-spezialsabelsageblatter':
        blades = SableSawBlade.objects.filter(group=group)
    elif slug == 'metallhandsageblatter':
        blades = HackSawBlade.objects.filter(group=group)
    elif slug == 'lochsagen':
        blades = HoleSaw.objects.all()
        other = HoleSawDiameter.objects.filter(advice=False)
    elif slug == 'metallsagebander':
        blades = BandSawBlade.objects.all()
        other = BandSawBladeIndicator.objects.all()
    elif slug == 'pendelhubstichsageblatter':
        blades = JigSawBlade.objects.all()
    elif slug == 'metallkreissageblatter':
        blades = CircularSawBlade.objects.all()
        other = CircularSawBladeIndicator.objects.all().order_by('diameter')
    return render(request, 'products/'+slug+'/overview.html',
                  {'blades': blades,
                   'group': group,
                   'other': other})


def details(request, slug, type):
    blade = SawBlade.objects.get(type=type)
    indicators = blade.indicators.order_by('width')
    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'clamping': blade.clamping,
                   'indicators': indicators})


def details_by_id(request, slug, id):
    """
    Given a slug and a ID it returns a unique blade
    :param slug: slug of productgroup
    :param id: blade id
    :return: blade
    """
    blade = BandSawBlade.objects.get(id=id)
    indicators = blade.bandsaw_indicators.all()

    return render(request, 'products/'+slug+'/details.html',
                  {'blade': blade,
                   'indicators': indicators})


def product_details(request, slug):
    return render(request, 'products/'+slug+'/details.html')


def product_advices(request, slug):
    objects = None
    if slug == 'lochsagen':
        objects = HoleSawDiameter.objects.filter(advice=True)
    return render(request, 'products/'+slug+'/advices.html', {'objects': objects})


def holesawAdvice(request):
    layout = 'holesaw_advice.html'
    diameters = HoleSawDiameter.objects.filter(advice=True)
    group = ProductGroup.objects.get(slug='lochsagen')
    return render(request, 'products/'+layout, {'diameters': diameters,
                                                'group': group})


# ======================================================================================================================
#
# ======================================================================================================================

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <!--<link rel="icon" href="../../favicon.ico">-->

  <title>GUHEMA GmbH & Co. KG</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <!-- Bootstrap theme -->
  <link rel="stylesheet" href="{% static 'assets/bootswatch/yeti.css' %}">

  <!-- Fontawesome CSS-->
  <link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.min.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <script src="{% static 'assets/jquery/jquery.min.js' %}"></script>

  <!-- Own Styles -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body role="document">
<!-- Fixed navbar -->
<nav class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
        <li><a href="{% url 'company' %}">{% trans "Unternehmen" %}</a></li>
        <li><a href="{% url 'products:index' %}">{% trans "Produkte" %}</a></li>
        <li><a href="{% url 'downloads:index' %}">{% trans "Kataloge" %}</a></li>
        {#        <li><a href="{% url 'fairs:index' %}">{% trans "Messen" %}</a></li>#}
        {#        <li><a href="{% url 'news:overview' %}">{% trans "News" %}</a></li>#}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <a href="{% url 'index' %}">
          <img id="logo" src="{% static 'img/logo/guhema80px.png' %}">
        </a>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div id="main">
  <div id="header-img-wrapper">
    <div class="container">
      {% block headerimg %}{% endblock %}
    </div>
  </div>

  <div class="container">
    {% block heading %}{% endblock %}
  </div>

  <div class="container padding-bottom" role="main">
    {% block content %}{% endblock %}
  </div>
</div>

{% if request.path == "/" %}
  <div class="blue-div">
    <div class="container">
      {% include 'productgroups.html' %}
      <div id="footer-line"></div>
    </div>
  </div>
{% endif %}

<div id="footer-wrapper">
  <div id="footer">
    <div id="footer-text" class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-6">
          &copy; {% now "Y" %} GUHEMA GmbH & Co. KG, <a href="mailto:info@guhema.com">info@guhema.com</a>, <a
            href="tel:+49 2191 8867 0">+49 2191 8867 0</a>
        </div>
        <div id="footer-kontakt-line" class="col-md-4 col-sm-6 col-xs-6 text-right">
          <a href="{% url 'impressum' %}">{% trans "Kontakt" %}</a> |
          <a href="{% url 'datenschutz' %}">{% trans "Datenschutz" %}</a> |
          <a href="{% url 'impressum' %}">{% trans "Impressum" %}</a>
        </div>
        <div class="col-md-2 col-sm-6 col-xs-6">
          {% get_language_info_list for LANGUAGES as languages %}
          <form action="{% url "set_language" %}" method="post" class="navbar-form navbar-right">
            {% csrf_token %}
            <div class="form-group">
              <select name="language" class="form-control" onchange="this.form.submit()">
                {% for language in languages %}
                  <option value="{{ language.code }}"
                          {% if language.code == LANGUAGE_CODE %}selected="selected"{% endif %}>
                    {{ language.name_local }}
                  </option>
                {% endfor %}
              </select>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% load static %}
{% load thumbnail %}

{% block headerimg %}
  <div id="header-img-text-wrapper">
    <img src="{% static 'img/header/header002.jpg' %}" alt="">
    <div id="header-text" class="hidden-xs hidden-sm">
      <h2>{% blocktrans %}METALLSÄGEBLÄTTER IN PERFEKTION{% endblocktrans %}</h2>
      <p>
        {% blocktrans %}Entdecken Sie unsere Produkte!{% endblocktrans %}
      </p>
    </div>
  </div>
{% endblock %}

{% block heading %}
  <h1>
    {% blocktrans %}Qualität die Vertrauen schafft{% endblocktrans %}<br>
    <small>{% blocktrans %}GUHEMA STEHT FÜR MADE IN GERMANY - UND DAS SEIT DEM JAHR 1867!{% endblocktrans %}</small>
  </h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <p>
        <strong>
          {% blocktrans %}Familientradition in der 5. Generation, langjährige Erfahrung, permanente Forschung und
            Entwicklung sowie fundiertes Spezialwissen stellen wir Ihnen zur Verfügung.{% endblocktrans %}
        </strong>
      </p>
      <p>
        {% blocktrans %}Mit unserer schlanken Organisation können wir jederzeit schnell auf Ihre individuellen Wünsche
          reagieren.{% endblocktrans %}
      </p>
      <p>
        {% blocktrans %}Unsere Unternehmensabläufe sind seit 1997 zertifiziert und entsprechen der Norm nach DIN EN ISO
          9001.{% endblocktrans %}
      </p>
      <p>
        {% blocktrans %}Also: Wenn Sie sich für ein GUHEMA-Produkt entscheiden, erhalten Sie ein Metallsägeblatt in
          Perfektion.{% endblocktrans %}
      </p>
      <p>
        <a href="{% url 'products:index' %}">
          <button type="button" class="btn text-normal">{% blocktrans %}Zu unseren Produkten{% endblocktrans %}
            &rsaquo;
          </button>
        </a>
      </p>
    </div>
  </div>

  {# News Section #}
  {% comment %}<h2 style="padding-top: 1em;">{% trans "News" %}</h2>
  {% include 'news/inc_overview.html' with posts=posts %}{% endcomment %}
{% endblock %}

templates/layout_productgroups.html
{% extends 'base.html' %}

{% block headerimg %}
  <div class="container">
    {% include 'productgroups.html' %}
  </div>
{% endblock %}

templates/productgroups.html
{% load i18n %}
{% load static %}

<div class="product-groups-wrapper" style="height: 180px">
  <div id="product-groups">
    <div class="row">
      <div class="col-md-4">
        <h3 class="text-white"><a href="{% url 'products:index' %}">{% trans "PRODUKTGRUPPEN" %}</a></h3>
      </div>
      <div class="col-md-8 text-right hidden-md hidden-sm hidden-xs">
        <a href="{% url 'products:list' slug='maschinensageblatter' %}"><img class="img-product-groups"
                                                                             src="{% static 'img/produktbilder/saege001.png' %}"
                                                                             data-toggle="tooltip" data-placement="top"
                                                                             title="{% trans "Maschinensägeblätter" %}"
                                                                             alt="{% trans "Maschinensägeblätter" %}"></a>
        <a href="{% url 'products:list' slug='metallstichsageblatter' %}"><img class="img-product-groups"
                                                                               src="{% static 'img/produktbilder/saege002.png' %}"
                                                                               data-toggle="tooltip"
                                                                               data-placement="top"
                                                                               title="{% trans "Metallstichsägeblätter" %}"
                                                                               alt="{% trans "Metallstichsägeblätter" %}"></a>
        <a href="{% url 'products:list' slug='sabel-und-spezialsabelsageblatter' %}"><img class="img-product-groups"
                                                                                          src="{% static 'img/produktbilder/saege003.png' %}"
                                                                                          data-toggle="tooltip"
                                                                                          data-placement="top"
                                                                                          title="{% trans "Säbel- und Spezialsäbelsägeblätter" %}"
                                                                                          alt="{% trans "Säbel- und Spezialsäbelsägeblätter" %}"></a>
        <a href="{% url 'products:list' slug='metallhandsageblatter' %}"><img class="img-product-groups"
                                                                              src="{% static 'img/produktbilder/saege004.png' %}"
                                                                              data-toggle="tooltip" data-placement="top"
                                                                              title="{% trans "Metallhandsägeblätter" %}"
                                                                              alt="{% trans "Metallhandsägeblätter" %}"></a>
        <a href="{% url 'products:list' slug='lochsagen' %}"><img class="img-product-groups"
                                                                  src="{% static 'img/produktbilder/saege005.png' %}"
                                                                  data-toggle="tooltip" data-placement="top"
                                                                  title="{% trans "Lochsägen" %}"
                                                                  alt="{% trans "Lochsägen" %}"></a>
        <a href="{% url 'products:list' slug='metallsagebander' %}"><img class="img-product-groups"
                                                                         src="{% static 'img/produktbilder/saege006.png' %}"
                                                                         data-toggle="tooltip" data-placement="top"
                                                                         title="{% trans "Metallsägebänder" %}"
                                                                         alt="{% trans "Metallsägebänder" %}"></a>
        <a href="{% url 'products:list' slug='pendelhubstichsageblatter' %}"><img class="img-product-groups"
                                                                                  src="{% static 'img/produktbilder/saege007.png' %}"
                                                                                  data-toggle="tooltip"
                                                                                  data-placement="top"
                                                                                  title="{% trans "Pendelhubstichsägeblätter" %}"
                                                                                  alt="{% trans "Pendelhubstichsägeblätter" %}"></a>
        <a href="{% url 'products:list' slug='metallkreissageblatter' %}"><img class="img-product-groups"
                                                                               src="{% static 'img/produktbilder/saege008.png' %}"
                                                                               data-toggle="tooltip"
                                                                               data-placement="top"
                                                                               title="{% trans "Metallkreissägeblätter" %}"
                                                                               alt="{% trans "Metallkreissägeblätter" %}"></a>
      </div>
    </div>
  </div>
</div>

<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })
</script>